/**
 * Bloom Framework - Auto-generated feature exports
 * 🤖 This file is automatically generated during build
 * @module @voilajsx/bloom/features
 * @file src/features/index.ts
 */

// Auto-discovered features
export { default as quotes } from './quotes/index';
export { default as webpages } from './webpages/index';

// Feature registry for runtime discovery
export const BLOOM_FEATURES = [
  'quotes',
  'webpages'
];

// Build-time feature metadata
export const BLOOM_FEATURE_META = {
  version: '1.0.0',
  buildTime: '2025-06-28T02:25:31.058Z',
  featuresCount: 2
};
